### Create Report
POST http://localhost:3000/reports
content-type: application/json

# {
#   "make": "BMW",
#   "model": "540i",
#   "year": 2019,
#   "mileage": 50000,
#   "lng": 0,
#   "lat": 0,
#   "price": 30000
# }
{
  "make": "Mercedes Benz",
  "model": "G63",
  "year": 2014,
  "mileage": 47432,
  "lng": 10,
  "lat": 15,
  "price": 180000
}


### Approval
PATCH http://localhost:3000/reports/12
Content-Type: application/json

{
  "approved": true
}

### GET estimate
GET http://localhost:3000/reports?make=Mercedes%20Benz&model=G63&lng=5&lat=10&mileage=48000&year=2016