### Create Report
POST http://localhost:3000/reports
content-type: application/json

# {
#   "make": "BMW",
#   "model": "540i",
#   "year": 2019,
#   "mileage": 50000,
#   "lng": 0,
#   "lat": 0,
#   "price": 30000
# }
{
  "make": "Mercedes Benz",
  "model": "G63",
  "year": 2016,
  "mileage": 27432,
  "lng": 0,
  "lat": 0,
  "price": 240000
}


### Approval
PATCH http://localhost:3000/reports/1
Content-Type: application/json

{
  "approved": false
}

### GET estimate
GET http://localhost:3000/reports?make=bmw&model=x5&lng=0&lat=0&mileage=48000&year=2016