### Create user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "test5@test.com",
  "password": "password"
}

### sign in
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "test5@test.com",
  "password": "password"
}

### find a user
GET http://localhost:3000/auth/5
content-type: application/json

### find all users
GET http://localhost:3000/auth?email=test@test.com
content-type: application/json

### delete a user
DELETE http://localhost:3000/auth/4
Content-Type: application/json

### update a user
PATCH http://localhost:3000/auth/5
Content-Type: application/json

{
  "email": "1@test.com",
  "password": "123"
}